### ISSUE TITLE
$api->user( $user_id ) returns null

### ISSUE THREAD

**Issue by rkorn86** [bluefeet/GitLab-API-v3#17]
See https://github.com/bluefeet/GitLab-API-v3/blob/master/lib/GitLab/API/v3.pm#L236
Correct return statement would be `return $self->get( $path );`

**Comment by rkorn86** [comment]
Workaround would be `my $user = $api->get( sprintf( '/users/%s', $user_id ) );`

**Comment by bluefeet** [comment]
Thanks!
