### ISSUE TITLE
merge_requests options

### ISSUE THREAD

**Issue by epa** [bluefeet/GitLab-API-v3#21]
It would be useful if `merge_requests()` accepted the optional parameters in the GitLab API, for example `merge_requests(123, state => 'opened')`.  See https://docs.gitlab.com/ee/api/merge_requests.html

**Comment by bluefeet** [comment]
The documentation at:

https://metacpan.org/pod/GitLab::API::v3#merge_requests

Says:

```
my $merge_requests = $api->merge_requests(
    $project_id,
    \%params,
);
```

Can you not do something like:

```
my $merge_requests = $api->merge_requests(
    $project_id,
    { state=>'opened' },
);
```

?

**Comment by epa** [comment]
I do apologize, I was looking at the documentation from an older version of the module by mistake despite having upgraded to 1.00.
