### ISSUE TITLE
GitLab API v3 deprecation 

### ISSUE THREAD

**Issue by agimenez** [bluefeet/GitLab-API-v3#24]
Hi,

The Release notes for version 8.17 (https://about.gitlab.com/2017/02/22/gitlab-8-17-released/) include a v3  API deprecation in favor of a new v4.

The current v3 API will stay there, but will only receive bug and security updates, no new features. Check the changes in https://docs.gitlab.com/ce/api/v3_to_v4.html

It would be nice to start thinking of implementing the new API version, and I guess a lot of code in this module will be useful for v4 (hence, no new module?).

If there is any way I can help you with this, I would be glad.

Regards!

**Comment by bluefeet** [comment]
Hey man!  Good to know, I didn't realize v3 was out!  Ya, I think I'll go ahead and fork this at GitLab::API::v4 and do some testing.

**Comment by Perler4P** [comment]
Hi,
any schedule for it in sight?
At the CERN portal one can read:
'API v3 is expected to stop working in August 2017.'

[https://cern.service-now.com/service-portal/view-outage.do?n=OTG0037271]

Regards!

**Comment by agimenez** [comment]
@bluefeet do you need any help with this?

**Comment by bluefeet** [comment]
I been triaging the pull requests in the queue the last couple days.  I want to get those in before forking as at that point the v3 module will be in bug-fix-only mode and we can get v4 knocked out.

**Comment by bluefeet** [comment]
Are there any wish-list items for the v4 module?  Here are mine:

- See if we can generate the module from Gitlab API specs (I'm 95% certain this is doable, just haven't dug into it).
- Write our own REST client.  Its easy-ish.  With Gitlab we know exactly what our inputs and outputs are and just need a fast HTTP library.

**Comment by agimenez** [comment]
Yeah, I don't think they use any spec like Swagger or similar. I think that they actually code manually everything (and autogenerate the docs), so either scrap the docs or... try to define a spec to keep it maintainable?

About the REST client, what's wrong with the current one (just asking, didn't have a deep look at the code)?

**Comment by bluefeet** [comment]
I thought with v4 they had moved to using something like Swagger.  Still need to find, I have something about it somewhere in my email.

Role::REST::Client has some weirdnesses to it.  Most recently in #28 it was a bit hackish to get it to support retries.  Just using HTTP::Tiny directly would make the code cleaner and easier to adjust at the protocol level.

**Comment by bluefeet** [comment]
Actually #26 is even more of a Role::REST::Client hack.  Had to mess with internals to get that one going.  :-/

**Comment by jjatria** [comment]
FWIW, I just made [PR #37 in Role::REST::Client](https://github.com/kaare/Role-REST-Client/pull/37), which should solve this problem for us (and allow for cleaner solutions should the need arise).

**Comment by jjatria** [comment]
That pull request has now been merged and released to CPAN.

When that version (0.20) becomes available, then the patch in #31 should provide a cleaner solution to #5

**Comment by bluefeet** [comment]
Hey guys, I'm finally getting back to this.  Going to try and move fast here to getting the v4 module done.

**Comment by bluefeet** [comment]
Allright, this is about ready to go live:
https://github.com/bluefeet/GitLab-API-v4

I'm going to close this issue now.  Any future discussion can happen here:
https://github.com/bluefeet/GitLab-API-v4/issues/1

Thanks!
