### ISSUE TITLE
RFC: Supporting personal snippets

### ISSUE THREAD

**Issue by d5ve** [bluefeet/GitLab-API-v3#25]
Hi,

GitLab 8.15 intorduced the concept of personal (non-project) snippets.

http://docs.gitlab.com/ce/user/snippets.html
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/api/snippets.md

I've forked GitLab-API-v3 to add the YML config for creating the person snippet methods.

The endpoint path for the personal snippets is `/snippets`, so the generated methods would make most sense named things like `snippets()`, `create_snippet()` etc. However those names are claimed by the existing project snippet operations.

Do you think it makes more sense to create the new person snippet methods prefixed by `personal_`, for example `personal_snippets()`,  and `create_personal_snippet()` to avoid the name clash. Or to rename the existing project snippets methods to add a `project_` prefix, for example `project_snippets()`, and `create_project_snippet()`?

The first option keeps backwards compatibility, so will be safest for existing users.

I can raise a pull request for either option.

Cheers,

Dave

**Comment by jjatria** [comment]
I'd go for the second option, the one that keeps backwards compatibility. But I'd name the methods `user_snippet`, etc. Not only is that shorter (50% fewer keystrokes!), but it also keeps the terminology used throughout the rest of the docs: `users`, `current_user`, `user`, etc...

In any case, this version of the API is on it's dying days (see #24), so for `v4` these methods can have more sensible names (with flashy warnings for those that upgraded by simply `s/v3/v4/`).

**Comment by bluefeet** [comment]
Thanks for the change @d5ve and the rational review @jjatria!  Closing this since the PR is merged.
