### ISSUE TITLE
$api->blob method fails during deserialization

### ISSUE THREAD

**Issue by cwigginton** [bluefeet/GitLab-API-v3#5]
This API client is excellent, and I'm enjoying using it, but I came across an issue when I was attempting to get the raw file content using the client $api->blob() method. I am consistently getting these errors:

> No serializer available for text/plain content. Trying default application/json at <perlpath>/Role/REST/Client.pm line 135.
> Couldn't deserialize data with application/json at <perlpath>/Role/REST/Client/Serializer.pm line 78.

The perl code I'm using to call the method in question is:

<pre>
my $gitlab = GitLab::API::v3->new(
    url => $apiUrl,
    token => $token,
);

my $projects = $gitlab->projects();
foreach my $project(@$projects)
{
    if ($project->{'path_with_namespace'} eq $projPathName)
    {
        my %p = ( 'filepath' => "file.pl" );
        my $ref = 'branchname';
        my $blob = $gitlab->blob(
            $project->{'id'},
            $ref,
            \%p
        );
        ...
    }
}
</pre>

"file.pl" and "branchname" are placeholders for the actual file and branch I'm using, and "$projPathName" is a simple conditional I'm using for testing. The correct use statements are also in place.

I am not getting any formatting errors from the API client, so I'm pretty sure I'm passing the content as it needs to be.

I was able to retrieve the content using curl to send the request on the Bash CL, using:

> curl -H "PRIVATE-TOKEN: (private token)" "http://(repo url)/api/v3/projects/:id/blobs/:sha?filepath=(path to file)"

I would be happy to provide more information if you like. Is there another approach I can take, or is there a way to handle plain text?

**Comment by bluefeet** [comment]
This can definitely be handled.  I'll take a look at it later tonight or in the morning.

**Comment by cwigginton** [comment]
Thank you!

On Tue, Jan 27, 2015 at 9:02 PM, Aran Deltac <notifications@github.com>
wrote:

> This can definitely be handled. I'll take a look at it later tonight or in
> the morning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bluefeet/GitLab-API-v3/issues/5#issuecomment-71781552>
> .
>



-- 
Thanks,

Chuck Wigginton
Developer
DYL, LLC

cwigginton@dyl.com

**Comment by bluefeet** [comment]
And I still haven't gotten to this.  Will do soon, but have busy weekend coming up!  :)

**Comment by cwigginton** [comment]
No worries. I had to move on my project, and decided to just use curl to
send my commands to the API.

Later on, I would like to use your client when we need more robust options,
but for the moment, there is no rush on this.

Thanks,
Chuck

On Wed, Feb 4, 2015 at 2:24 PM, Aran Deltac <notifications@github.com>
wrote:

> And I still haven't gotten to this. Will do soon, but have busy weekend
> coming up! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bluefeet/GitLab-API-v3/issues/5#issuecomment-72953123>
> .
>



-- 
Thanks,

Chuck Wigginton
Developer
DYL, LLC

cwigginton@dyl.com

**Comment by jjatria** [comment]
I came across a similar problem with `$api->archive()`:

> No serializer available for application/x-gzip content. Trying default application/json at /usr/local/share/perl/5.18.2/Role/REST/Client.pm line 135.
Couldn't deserialize data with application/json at /usr/local/share/perl/5.18.2/Role/REST/Client/Serializer.pm line 78

so whatever is affecting `blob()` is affecting other methods as well.

**Comment by c1mark** [comment]
Hi,

I've hit the same problem today when using:

my $api = GitLab::API::v3->new(
    url   => $v3_api_url,
    token => $token,
);

my $projects = $api->projects();

The error is:

No serializer available for text/plain content. Trying default application/json at /usr/local/share/perl5/Role/REST/Client.pm line 135.
Couldn't deserialize data with application/json at /usr/local/share/perl5/Role/REST/Client/Serializer.pm line 78.

The strange thing is, this is working on another box. The working one is RHEL 5 and the failing one is RHEL 6. I assume that's not significant though with this being perl?

I had to build the GitLab-API module by hand on both servers (oh the joys of living behind firewalls), so it's very possible I've made an error somewhere. 

Does anyone have any advice they can offer please?

**Comment by c1mark** [comment]
My original problem above turned out to be a red herring. After looking at the perl traces for the working and non-working machines, I found that the real problem was that I was connecting to a gitlab server using https. It turns out for gitlab api to work with an https connection, you need the IO-Socket-SSL module. It then worked fine, so I assume the API call was just getting back nothing and not detecting the SSL error. Perhaps this module should be added to the pre-reqs?

**Comment by c1mark** [comment]
@jjatria 

I know have the same issue getting an archive.

**Comment by bluefeet** [comment]
I'd like to avoid adding a new dependency which isn't strictly required.  I'll see about reproducing the error and modifying the code to detect the SSL error and report it in a friendly manner.

**Comment by jjatria** [comment]
I don't think this is, at its core, an SSL error. @c1mark stated that, even after solving the SSL dependency, he was still having problems with `archive()` (like I do).

Indeed, I _have_ `IO::Socket::SSL` installed, and my problem persists. And I don't know about the issue reported by @cwigginton, but I would imagine it would also remain unsolved even with that module.

**Comment by c1mark** [comment]
Just to clarify. I think we have two issues here. One is not detecting SSL errors, and the other is the deserialization issue. I don't think they are related. 

For my deserialization issue, I have switched to using curl for now the same as @cwigginton

**Comment by bluefeet** [comment]
OK so I spent the last couple hours digging deep into this.  The archive, blobs, and raw_blobs endpoints all return base64 encoded JSON about the thing being requested, NOT the thing itself.  Neither the blobs or raw_blobs returns the actual file contents.  The archive endpoint returns JSON containing the local filesystem path to the archive.  I'm really perplexed by this as it seems to contradict the documentation (the docs say it returns the contents, at least in the *blobs case).

I even tried the curl example @cwigginton posted originally and I get the same base64 encoded JSON back.  Is this what you guys are expecting?  I was expecting actual file contents.  If this is correct, that getting this JSON is correct, then should I be decoding it and returning the data structure?

Its weird, with blobs I get something like this:
git-blob:base64string

And with archive I get:
"git-archive:base64string"

Notice archive returns double quotes around it.  Why the inconsistency?  So funky.  And if its just JSON why not just make it work like any other endpoint that return application/json?

Any thoughts appreciated.

 - confused

**Comment by dralexk** [comment]
Hello,

I have a similar problem. 

I have a program, which creates new issues using the $api->create_issue method. The program works well with several GitLab servers, but when I run it with githost.io, I get the error:

> Generating issues...
> No serializer available for text/plain content. Trying default application/json at /usr/local/share/perl5/Role/REST/Client.pm line 142.
> Couldn't deserialize data with application/json at /usr/local/share/perl5/Role/REST/Client/Serializer.pm line 78.
> Error POSTing /projects/<groupname>%2F<projectname>/issues from https://almtoolbox.githost.io/api/v3 (HTTP 599): Internal Exception {} at /usr/local/share/perl5/GitLab/API/v3.pm line 1625
> 

Here is the full program:

`#!/usr/bin/perl
use strict;
use warnings;

use GitLab::API::v3;
my $v3_api_url = "http://almtoolbox.githost.io/api/v3";
my $token = "mytoken";
	
my $api = GitLab::API::v3->new(
	url   => $v3_api_url,
	token => $token,
);

my $datestring = localtime();
print "Local date and time $datestring\n";

print "Generating issues...\n";

for (my $i = 1; $i <= 1000; $i++) 
{
	my %params = (
		title => "Test issue #$i",
		description => "Lorem ipsum dolor sit amet."
	);
	my $issue = $api->create_issue(
		"<groupname>/<projectname>",
		\%params);
	print "Issue #$i created!\n";
	
}

$datestring = localtime();
print "Local date and time $datestring\n";
`

**Comment by jjatria** [comment]
I just made PR #26 which fixes this issue locally, by disabling deserialisation of non-serial data. The solution is a bit hackish, but it's nice in that the decision to serialise or not depends on the content-type of the response.
