### ISSUE TITLE
Error 599

### ISSUE THREAD

**Issue by nf-contribute** [bluefeet/GitLab-API-v3#8]
I'm running GitLab::API::v3 version 0.08

I'm getting an error from here:
https://github.com/bluefeet/GitLab-API-v3/blob/v0.08/lib/GitLab/API/v3/RESTClient.pm#L45

Here is my call stack in perl:
Carp::confess                            | /usr/share/perl/5.14.2/Carp.pm                           | 80  
GitLab::API::v3::RESTClient::**ANON**    | /usr/local/share/perl/5.14.2/GitLab/API/v3/RESTClient.pm | 44  
GitLab::API::v3::RESTClient::**ANON**    | ---              | 1  
GitLab::API::v3::RESTClient::get         | ---  | 2  
GitLab::API::v3::get                     | ---      | 17  
GitLab::API::v3::commit                  | /usr/local/share/perl/5.14.2/GitLab/API/v3.pm            | 1393

This is after my script does this:

```
my $commit = $api->commit("mygroup/myrepo", "1234567890123456789012345678901234567890");
```

Here is the error returned by the Carp::confess:

```
Error GETing /projects/mygroup%2Fmyrepo/repository/commits/r16919 from http://git/api/v3 (HTTP 599): Internal Exception {} at (eval 1680) line 17
```

I'm not entirely sure what is failing, I think it's just nginx closing the connection at some randomly wrong time or something. This error only appears maybe 1 out of every 100 API calls. After I make the same exact request again (via reloading the webpage I have making the call), it works fine and goes away. Is there any way to have GitLab retry for cases like these?

**Comment by bluefeet** [comment]
Adding a configurable retry sounds like a great idea.

**Comment by jjatria** [comment]
I just made PR #28 that adds a retry mechanic for responses with codes in the `500` block. Not sure if this is what you had in mind, but it's a possibility!

**Comment by bluefeet** [comment]
I'm pretty sure this is the only way we can handle this issue, so I'm going to close.  Please re-open or open a new issue if #28 does not resolve your issue.
